# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main
- releases/*



variables:
 - name: imageNameaaa
   value: "windows-latest"
 - name: jdkVersion
   value: "1.10"
 - group: secretrotation

pool:
  vmImage: $(imageNameaaa)



steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "REACT_APP_ATOM_API_ENDPOINT = $(REACT-APP-ATOM-API-ENDPOINT)" >> temp.txt
      echo "REACT_APP_ATOM_API_CODE = $(REACT-APP-ATOM-API-CODE)" >> temp.txt
      echo "REACT_APP_AUTH_LOGIN_REDIRECT_URI = $(REACT-APP-AUTH-LOGIN-REDIRECT-URI)" >> temp.txt
      echo "REACT_APP_AUTH_LOGOUT_REDIRECT_URI = $(REAC-APP-AUTH-LOGOUT-REDIRECT-URI)" >> temp.txt
      echo "REACT_APP_AUTH_CLIENTID = $(REACT-APP-AUTH-CLIENTID)" >> temp.txt
      echo "REACT_APP_AUTH_AUTHORITY = $(REACT-APP-AUTH-AUTHORITY)" >> temp.txt
      echo "REACT_APP_ATOM_AUTH_ENTERPRISE_APP_ID = $(REACT-APP-ATOM-AUTH-ENTERPRISE-APP-ID)" >> temp.txt
      echo "REACT_APP_ATOM_AUTH_APP_REGISTRATION_ID = $(REACT-APP-ATOM-AUTH-APP-REGISTRATION-ID)" >> temp.txt
      
      cat temp.txt
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: $(jdkVersion)
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: "JaCoCo"
    summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/site/jacoco/jacoco.xml"
    reportDirectory: "$(System.DefaultWorkingDirectory)/**/site/jacoco"
    failIfCoverageEmpty: true

- task: AzureFileCopy@4
  inputs:
    SourcePath: 'temp.txt'
    azureSubscription: 'MVET-R&D(85345bf7-3fb6-447d-86da-7c11a68ee27b)'
    Destination: 'AzureBlob'
    storage: 'secretrotationrgstorage2'
    ContainerName: 'envvars'