# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main
- releases/*



variables:
 - name: imageNameaaa
   value: "ubuntu-latest"
 - name: jdkVersion
   value: "1.10"
 - group: secretrotation

pool:
  vmImage: $(imageNameaaa)



steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "REACT_APP_ATOM_API_ENDPOINT = $(REACT-APP-ATOM-API-ENDPOINT)" >> temp.txt
      echo "REACT_APP_ATOM_API_CODE = $(REACT_APP_ATOM_API_CODE)" >> temp.txt
      echo "REACT_APP_AUTH_LOGIN_REDIRECT_URI = $(REACT_APP_AUTH_LOGIN_REDIRECT_URI)" >> temp.txt
      echo "REACT_APP_AUTH_LOGOUT_REDIRECT_URI = $(REACT_APP_AUTH_LOGOUT_REDIRECT_URI)" >> temp.txt
      echo "REACT_APP_AUTH_CLIENTID = $(REACT_APP_AUTH_CLIENTID)" >> temp.txt
      echo "REACT_APP_AUTH_AUTHORITY = $(REACT-APP-AUTH-AUTHORITY)" >> temp.txt
      echo "REACT_APP_ATOM_AUTH_ENTERPRISE_APP_ID = $(REACT_APP_ATOM_AUTH_ENTERPRISE_APP_ID)" >> temp.txt
      echo "REACT_APP_ATOM_AUTH_APP_REGISTRATION_ID = $(REACT_APP_ATOM_AUTH_APP_REGISTRATION_ID)" >> temp.txt
      cat temp.txt
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: $(jdkVersion)
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: "JaCoCo"
    summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/site/jacoco/jacoco.xml"
    reportDirectory: "$(System.DefaultWorkingDirectory)/**/site/jacoco"
    failIfCoverageEmpty: true
